name = "JSONSchema"
uuid = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
version = "2.0.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
Downloads = "1"
JSON = "1"
StructUtils = "2"
URIs = "1"
julia = "1.10"
